alerts:
- active: false
  auto_reset: false
  condition: above
  id: 1
  max_triggers: 1
  name: 黄金期货
  symbol: AU0
  target_price: 580
- active: true
  auto_reset: false
  condition: below
  id: 2
  max_triggers: 1
  name: 白银期货
  symbol: AG0
  target_price: 7500
- active: false
  auto_reset: false
  condition: below
  id: 3
  max_triggers: 1
  name: 生猪现货
  symbol: spot_pork
  target_price: 15000
- active: true
  auto_reset: false
  condition: below
  id: 4
  max_triggers: 1
  name: 黄金期货
  symbol: AU0
  target_price: 850
- active: false
  auto_reset: false
  condition: below
  id: 5
  max_triggers: 1
  name: 牧原股份
  symbol: sz002714
  target_price: 30
